name: json_forms_renderer
description: "A Flutter package to render forms from JSON Schema based on https://jsonforms.io"
version: 1.0.0
homepage: https://pyck.ai/
repository: https://github.com/pyck-ai/json-forms-renderer-flutter

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0